name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login Docker
      run: docker login -u masluse -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build -t $DOCKER_REPOSITORY:latest .
    - name: Push Docker image
      run: docker push $DOCKER_REPOSITORY:latest
