name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login into Docker Hub
      run: docker login -u masluse -p ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:latest .
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest

